#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
# Run: uv run scripts/im2p_config.py --check | --generate | --profile A W DIM | --rust A W DIM
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from typing import Final, TypedDict

ROOT: Final = Path(__file__).resolve().parents[1]
SOURCE: Final = ROOT / "config/im2p_profiles.json"
BSV: Final = ROOT / "src/common/Config.bsv"
HEADER: Final = ROOT / "sim/ffi/im2p_config.h"


class ProfileConfig(TypedDict):
    activation_bits: int
    weight_bits: int
    dim: int
    product_bits: int
    partial_bits: int
    accumulator_bits: int
    accumulator_rows: int
    row_address_bits: int
    row_count_bits: int
    logical_capacity_bytes: int
    memory_backend: str
    memory_read_latency: int
    memory_latency_contract: str
    numerical_semantics_revision: str
    config_source_sha256: str
    generated_config_sha256: str


class ConfigError(ValueError):
    pass


def config_fingerprint() -> str:
    return hashlib.sha256(SOURCE.read_bytes() + Path(__file__).read_bytes()).hexdigest()


def profile_config(activation_bits: int, weight_bits: int, dim: int) -> ProfileConfig:
    source = json.loads(SOURCE.read_text(encoding="utf-8"))
    widths: dict[str, int] = source["integer_accumulator_bits"]
    if source["schema"] != 1:
        raise ConfigError("unsupported profile schema")
    if activation_bits != weight_bits or str(activation_bits) not in widths or dim not in source["dimensions"]:
        raise ConfigError(f"unsupported profile: A{activation_bits}/W{weight_bits}/DIM{dim}")
    accumulator_bits = widths[str(activation_bits)]
    capacity = int(source["logical_capacity_bytes"])
    rows, remainder = divmod(capacity * 8, dim * accumulator_bits)
    if remainder or rows < dim or rows & (rows - 1):
        raise ConfigError("accumulator capacity must yield power-of-two rows >= DIM")
    generated = generated_files()
    for path, content in generated.items():
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            raise ConfigError(f"stale generated configuration: {path}; run --generate")
    return ProfileConfig(
        activation_bits=activation_bits, weight_bits=weight_bits, dim=dim,
        product_bits=activation_bits + weight_bits, partial_bits=accumulator_bits,
        accumulator_bits=accumulator_bits, accumulator_rows=rows,
        row_address_bits=(rows - 1).bit_length(), row_count_bits=dim.bit_length(),
        logical_capacity_bytes=capacity, memory_backend=str(source["memory_backend"]),
        memory_read_latency=int(source["memory_read_latency"]),
        memory_latency_contract=str(source["memory_latency_contract"]),
        numerical_semantics_revision=str(source["numerical_semantics_revision"]),
        config_source_sha256=config_fingerprint(),
        generated_config_sha256=hashlib.sha256("".join(generated.values()).encode()).hexdigest(),
    )


def generated_files() -> dict[Path, str]:
    source = json.loads(SOURCE.read_text(encoding="utf-8"))
    widths: dict[str, int] = source["integer_accumulator_bits"]
    capacity = int(source["logical_capacity_bytes"])
    fingerprint = config_fingerprint()
    bsv = ["// Generated by scripts/im2p_config.py; edit config/im2p_profiles.json.",
           f"// Configuration SHA256: {fingerprint}", "package Config;", "",
           "typedef 16 DefaultArrayDim;", "typedef 1 DefaultPeLatency;", "typedef 16 DefaultVectorLanes;",
           "// Exact local dot-product width; architectural accumulator widths stay separate.",
           "typedef TAdd#(productWidth, TLog#(dim)) IntegerPartialWidth#(numeric type dim, numeric type productWidth);",
           f"typedef {capacity} IntegerAccumulatorCapacityBytes;",
           "typedef TDiv#(TMul#(IntegerAccumulatorCapacityBytes, 8), TMul#(dim, width)) IntegerAccumulatorRows#(numeric type dim, numeric type width);",
           f"typedef {source['fp_accumulator_rows']} FloatingAccumulatorRows;", ""]
    header = ["// Generated by scripts/im2p_config.py; edit config/im2p_profiles.json.",
              "#ifndef IM2P_GENERATED_CONFIG_H", "#define IM2P_GENERATED_CONFIG_H", "",
              f"#define IM2P_CONFIG_SHA256 \"{fingerprint}\"",
              f"#define IM2P_LOGICAL_CAPACITY_BYTES {capacity}",
              f"#define IM2P_MEMORY_BACKEND \"{source['memory_backend']}\"",
              f"#define IM2P_MEMORY_READ_LATENCY {source['memory_read_latency']}",
              f"#define IM2P_MEMORY_LATENCY_CONTRACT \"{source['memory_latency_contract']}\"",
              f"#define IM2P_NUMERICAL_SEMANTICS_REVISION \"{source['numerical_semantics_revision']}\"", ""]
    for index, (precision, width) in enumerate(widths.items()):
        bsv.extend([f"typedef {precision} A{precision}InputWidth;",
                    f"typedef {precision} A{precision}WeightWidth;",
                    f"typedef {2 * int(precision)} A{precision}ProductWidth;",
                    f"typedef {width} A{precision}AccumulatorWidth;", ""])
        header.extend([f"#{'if' if index == 0 else 'elif'} IM2P_ACTIVATION_BITS == {precision} && IM2P_WEIGHT_BITS == {precision}",
                       f"#define IM2P_ACCUMULATOR_BITS {width}"])
    bsv.extend(["typedef A8InputWidth DefaultInputWidth;", "typedef A8WeightWidth DefaultWeightWidth;",
                "typedef A8ProductWidth DefaultProductWidth;", "typedef A8AccumulatorWidth DefaultAccumulatorWidth;",
                "typedef 8 DefaultScaleWidth;",
                "typedef IntegerAccumulatorRows#(DefaultArrayDim, DefaultAccumulatorWidth) DefaultAccumulatorRows;", "", "endpackage", ""])
    header.extend(["#else", '#error "unsupported IM2P activation/weight profile"', "#endif",
                   "#define IM2P_PARTIAL_BITS IM2P_ACCUMULATOR_BITS",
                   "#define IM2P_ACCUMULATOR_ROWS (IM2P_LOGICAL_CAPACITY_BYTES * 8 / (IM2P_DIM * IM2P_ACCUMULATOR_BITS))", ""])
    for index, dim in enumerate(source["dimensions"]):
        header.extend([f"#{'if' if index == 0 else 'elif'} IM2P_DIM == {dim}",
                       f"#define IM2P_ROW_COUNT_BITS {int(dim).bit_length()}"])
        for width_index, width in enumerate(sorted(set(widths.values()))):
            header.extend([f"#{'if' if width_index == 0 else 'elif'} IM2P_ACCUMULATOR_BITS == {width}",
                           f"#define IM2P_ROW_ADDRESS_BITS {(capacity * 8 // (int(dim) * width) - 1).bit_length()}"])
        header.append("#endif")
    header.extend(["#else", '#error "unsupported IM2P DIM"', "#endif", "", "#endif", ""])
    return {BSV: "\n".join(bsv), HEADER: "\n".join(header)}


def main() -> int:
    args = sys.argv[1:]
    usage = "usage: im2p_config.py --check | --generate | --profile A W DIM | --rust A W DIM"
    if args in (["--help"], ["-h"]):
        print(usage)
        return 0
    if args in (["--generate"], ["--check"]):
        for path, content in generated_files().items():
            if args == ["--generate"]:
                path.write_text(content, encoding="utf-8")
            elif not path.is_file() or path.read_text(encoding="utf-8") != content:
                raise ConfigError(f"stale generated configuration: {path}; run --generate")
        return 0
    if len(args) == 4 and args[0] in ("--profile", "--rust"):
        profile = profile_config(*map(int, args[1:]))
        if args[0] == "--profile":
            print(json.dumps(profile, sort_keys=True, indent=2))
        else:
            for key, value in profile.items():
                rust_type = "usize" if isinstance(value, int) else "&str"
                print(f"pub const IM2P_{key.upper()}: {rust_type} = {json.dumps(value)};")
        return 0
    print(usage, file=sys.stderr)
    return 2


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (ConfigError, ValueError) as error:
        sys.exit(str(error))
