// Generated by scripts/im2p_config.py; edit config/im2p_profiles.json.
// Configuration SHA256: ad9b2c2d6244c037405f03cb7fc74fc7f129a59d4a055879e972ed6f7abe8ad0
package Config;

typedef 16 DefaultArrayDim;
typedef 1 DefaultPeLatency;
typedef 16 DefaultVectorLanes;
typedef 65536 IntegerAccumulatorCapacityBytes;
typedef TDiv#(TMul#(IntegerAccumulatorCapacityBytes, 8), TMul#(dim, width)) IntegerAccumulatorRows#(numeric type dim, numeric type width);
typedef 256 FloatingAccumulatorRows;

typedef 4 A4InputWidth;
typedef 4 A4WeightWidth;
typedef 8 A4ProductWidth;
typedef 32 A4AccumulatorWidth;

typedef 8 A8InputWidth;
typedef 8 A8WeightWidth;
typedef 16 A8ProductWidth;
typedef 32 A8AccumulatorWidth;

typedef 16 A16InputWidth;
typedef 16 A16WeightWidth;
typedef 32 A16ProductWidth;
typedef 64 A16AccumulatorWidth;

typedef A8InputWidth DefaultInputWidth;
typedef A8WeightWidth DefaultWeightWidth;
typedef A8ProductWidth DefaultProductWidth;
typedef A8AccumulatorWidth DefaultAccumulatorWidth;
typedef 8 DefaultScaleWidth;
typedef IntegerAccumulatorRows#(DefaultArrayDim, DefaultAccumulatorWidth) DefaultAccumulatorRows;

endpackage
