// Generated by scripts/im2p_config.py; edit config/im2p_profiles.json.
// Configuration SHA256: 091175baa1660ccb15702aca4a28d1a586aab52f460b78fa8495432b0ffb0fd9
package Config;

typedef 16 DefaultArrayDim;
typedef 1 DefaultPeLatency;
typedef 16 DefaultVectorLanes;
// Exact local dot-product width; architectural accumulator widths stay separate.
typedef TAdd#(productWidth, TLog#(dim)) IntegerPartialWidth#(numeric type dim, numeric type productWidth);
typedef 65536 IntegerAccumulatorCapacityBytes;
typedef TDiv#(TMul#(IntegerAccumulatorCapacityBytes, 8), TMul#(dim, width)) IntegerAccumulatorRows#(numeric type dim, numeric type width);
typedef 256 FloatingAccumulatorRows;

typedef 4 A4InputWidth;
typedef 4 A4WeightWidth;
typedef 8 A4ProductWidth;
typedef 32 A4AccumulatorWidth;

typedef 8 A8InputWidth;
typedef 8 A8WeightWidth;
typedef 16 A8ProductWidth;
typedef 32 A8AccumulatorWidth;

typedef 16 A16InputWidth;
typedef 16 A16WeightWidth;
typedef 32 A16ProductWidth;
typedef 64 A16AccumulatorWidth;

typedef A8InputWidth DefaultInputWidth;
typedef A8WeightWidth DefaultWeightWidth;
typedef A8ProductWidth DefaultProductWidth;
typedef A8AccumulatorWidth DefaultAccumulatorWidth;
typedef 32 DefaultScaleWidth;
typedef IntegerAccumulatorRows#(DefaultArrayDim, DefaultAccumulatorWidth) DefaultAccumulatorRows;

endpackage
